### PR TITLE
Update call activity to use multiselect

### LINKED ISSUE #706: Inspector select dropdown needs to be vue-multiselect for filtering

### PR DESCRIPTION
**Pull request by chipit24**
Fixes #706.

This PR requires the changes in https://github.com/ProcessMaker/vue-form-elements/pull/105 to be merged and published before merging this PR. Tests may be failing until that happens.

Screen Shot 2019-10-02 at 2 02 48 PM

### CODE REVIEW

**Comment by chipit24** [comment]
Just noticed a bug when de-selecting a process in the list:
```
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'value' of null"
```

You can hold off on reviewing until I fix this.

**Comment by JCook21** [comment]
@chipit24 I don't think this can be merged until the changes in the upstream component are published. We need to keep our repo in a state where tests are passing.

**Comment by chipit24** [comment]
@JCook21 Yup–I mentioned that in the PR description but I should have kept this in a draft to prevent it from being accidentally merged.

**Comment by JCook21** [comment]
One comment on the screenshot above: the highlight colour on the selected element seems to be green. Does this match the colour scheme of the modeler?

**Comment by chipit24** [comment]
@JCook21 Is there some colour scheme you are referring to? I'm not aware of any colour scheme that this should match, and it appears that the same green is used across all other multiselects.

**Comment by JCook21** [comment]
> @JCook21 Is there some colour scheme you are referring to? I'm not aware of any colour scheme that this should match, and it appears that the same green is used across all other multiselects.

@chipit24 my bad, sorry. I didn't remember seeing that green anywhere else but I must be mistaken.

**Comment by chipit24** [comment]
@JCook21 There are some differences in the bootstrap theme between standalone and processmaker, so it's good that you brought that up, as this PR shouldn't cause a colour change. I checked the colours in processmaker and everything appears as it should.

**Pull request merged**
