### PR TITLE
FOUR-8994: Pointer issues fixed

### PR DESCRIPTION
**Pull request by TinCodes**
## Issue & Reproduction Steps

1. Go to modeler
2. Open the Explorer rail
3. Click on any element of Explorer rail
4. Click on another element of Bottom rail
5. Click the element selected in the canvas

Expected behavior: 
The arrow cursor should not disappear of mouse pointer after releasing the element on the canvas.

Actual behavior: 
The Arrow cursor disappears in mouse pointer.

## Solution
- Changed the timing for the emit that controls the change in pointer style.

## How to Test
Test the steps above

## Related Tickets & Packages
- [FOUR-8994](https://processmaker.atlassian.net/browse/FOUR-8994)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-8994]: https://processmaker.atlassian.net/browse/FOUR-8994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-7dea049878.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-7dea049878.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-7dea049878.eng.processmaker.net

**Review by danloa — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-7dea049878.eng.processmaker.net

**Review by josechirivella — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-7dea049878.eng.processmaker.net

**Pull request merged**
