### PR TITLE
Add BPMN diagram validation to status bar

### LINKED ISSUE #196: BPMN Lint
Let's explore how to use and implement this linter to validate the BPMN. Let's discuss before any implementation.

https://github.com/bpmn-io/bpmnlint

https://github.com/camunda/bpmnlint-plugin-camunda#readme

### PR DESCRIPTION
**Pull request by chipit24**
Fixes #196.

**How to test:**
 * Click the "Validate Diagram" button in the top right of the grid.
 * With only the start event present, there should be two BPMN lint errors logged to the console.
 * If you add an end event and connect the start event to it, all validation errors should be resolved.

**Important changes:**
 * Added two new packages (make sure to run `npm i` before testing):
   - https://github.com/bpmn-io/bpmnlint
   - https://github.com/nikku/bpmnlint-loader
 * This PR modifies the `ModelerApp.vue` file, which is not exported after building. A separate PR will need to be created to merge the changes to `ModelerApp.vue` into https://github.com/ProcessMaker/bpm.

### CODE REVIEW

**Comment by chipit24** [comment]
WIP pending feedback on validation presentation. Where, and how, should the validation errors be shown: in status bar, popup, next to element, etc?

**Comment by chipit24** [comment]
Updated PR; current validation status is now reflected in the status bar component:
screen shot 2019-02-11 at 2 16 25 pm
screen shot 2019-02-11 at 2 16 40 pm

**Comment by velkymx** [comment]
@chipit24 please fix conflicts and let me know when I can review.

**Comment by chipit24** [comment]
@velkymx Conflicts have been resolved.

**Comment by chipit24** [comment]
This is the "base PR" that https://github.com/ProcessMaker/modeler/pull/218 and https://github.com/ProcessMaker/modeler/pull/216 branched off of. Since those PRs are now merged and contain the changes in this PR, this PR can now be closed.

**Pull request closed without merging**
