### PR TITLE
Improve inspector layout via accordions

### LINKED ISSUE #525: Inspector Layout
Here is a master list for how all element inspectors should be organized.

[Modeler Control Inspectors.pdf](https://github.com/ProcessMaker/modeler/files/3507336/Modeler.Control.Inspectors.pdf)

- [x] Task
- [x] Manual Task
- [x] Script Task
- [x] End Event
- [x] Intermediate Timer Event
- [x] Start Event
- [x] Start Timer Event
- [x] Exclusive Gateway
- [x] Exclusive Gateway Flow Elements
- [x] Inclusive Gateway
- [x] Inclusive Gateway Flow Elements
- [x] Parallel Gateway
- [x] Parallel Gateway Flow Elements
- [x] Call Activity
- [x] Pool
- [x] Lane
- [x] Text Annotation

### PR DESCRIPTION
**Pull request by ryancooley**
## Changes
- Introduces the Advanced accordion menu to every node's inspector
- Fixes two tests that needed an open accordion menu to pass
- Fixed the long-running misspelling of "configuration"
- Updates to vue-form-elements v0.10.11

Closes #525, #578.

### CODE REVIEW

**Comment by sanjacornelius** [comment]
New Event-Based Gateway & Intermediate Message Catch Event accordion styles need to be updated. 

Everything else looks great!

**Comment by JCook21** [comment]
@ryancooley @velkymx @sanjacornelius do we want this to be merged and to go out as part of the next release on Friday? I just want to make sure as this work hasn't been part of the QA run on modeler this week. If not it might be better to hold off merging this until Monday.

**Comment by chipit24** [comment]
Keeping PRs smaller makes reviewing easier and faster, and makes it easier to track down bugs in the future. Going forward, unless tickets are actually tightly coupled, lets ensure separate issues are resolved in separate PRs.

In this case, we already have a PR for updating dependencies (https://github.com/ProcessMaker/modeler/pull/574), and #578 (_Fixed the long-running misspelling of "configuration"_) was already being worked on in another PR: https://github.com/ProcessMaker/modeler/pull/579.

There's no benefit in clumping 3 separate issues into one PR, even if two of the issues are successfully resolved, the PR will need to be held up if there's problems with the 3rd issue.

**Comment by ryancooley** [comment]
@robert Understood.  In this case, the dependency updated was necessary for this particular ticket and for specs to pass. However, good point about the configuration spelling. Should've been a separate ticket.

**Comment by chipit24** [comment]
Although this PR makes progress towards https://github.com/ProcessMaker/modeler/issues/525, I don't think it resolves it completely. The PDF linked in that issue describes more than just _Configuration_ and _Advanced_ accordions, for example:

Screen Shot 2019-08-29 at 2 32 13 PM

Task also requires _Assignment Rules_ and _Notifications_ accordions. @ryancooley Was this intentionally left out in this PR or did you mean to add it? If the former, then I'll update the PR comment to reference (as oppose to close) the issue, which can be wrapped up in another PR.

**Comment by ryancooley** [comment]
@chipit24 Those changes are addressed in ProcessMaker/processmaker#2341 since many of those panels were being injected there.

**Pull request merged**
