### PR TITLE
FOUR-8764 Added Github Actions

### PR DESCRIPTION
**Pull request by josechirivella**
## Issue & Reproduction Steps

Expected behavior: 
Our CI/CD pipeline should be able to run in Github Actions

Actual behavior: 
Currently running on CircleCi

## Solution
-

## How to Test
Test the steps above

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-8764
- https://processmaker.atlassian.net/browse/FOUR-8782

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-7022fe24b7.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-7022fe24b7.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-7022fe24b7.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed 2023-06-23T21:08:15+00:00

**Review by nolanpro — APPROVED** [review]

**Comment by ana-mauricio** [comment]
Locally the e2e tests are working 
image
after seeing the errors in CI tests have not been run, It seems there are error in  commands that are failing with CI. 
image
@josechirivella

**Comment by ana-mauricio** [comment]
The suits VerifyARecalculationFiresFlowsAreLocatedImproperlyOnTheDiagram && BoundaryEventValidation.cy.js were corrected
@josechirivella @ryancooley

**Comment by josechirivella** [comment]
Yup, that makes Github happy. Thanks @ana-mauricio 🥳

**Pull request merged**
