### PR TITLE
Add modal with svg preview for subprocesses

### LINKED ISSUE #1288: Click on [+] opens the subprocess SVG
Click on [+] opens the subprocess SVG in a modal with a link to open that process in a new window.

- [x] Find the endpoint that returns the SVG for a process given the process ID
- [x] Render the SVG in a modal
- [x] Add an event handler to the Call Activity [+] marker that opens the model
- [x] Add a link in the modal which opens the subprocess in a new window

### PR DESCRIPTION
**Pull request by vehikl-jacare**
Fixes #1288.

This PR will allow the user to click the [+] button on the subprocess that will open a modal window with a preview of the called process. 

Screen Shot 2020-12-09 at 1 54 28 PM

This PR is dependent on [this PR in Processmaker](https://github.com/ProcessMaker/processmaker/pull/3556)

### CODE REVIEW

**Review by velkymx — CHANGES_REQUESTED** [review]
Can we center the SVG in the modal?

**Comment by johnblackspear** [comment]
@velkymx We can improve it some, but the SVG is stored with some of the empty canvas in it.

We tried some ideas and it doesn't really look centered (some extra debugging added so that you can see the SVG)

Screen Shot 2020-12-14 at 12 02 16

We can do that? 
We can also do that and maybe add a little border around the SVG, something like:

Screen Shot 2020-12-14 at 12 06 25

**Comment by velkymx** [comment]
That's fine. Let's merged.

**Comment by vehikl-jacare** [comment]
Hi @velkymx tests are running, but we've updated to output the svg like this:

Screen Shot 2020-12-15 at 9 32 59 AM

**Pull request merged**
