### PR TITLE
Update styles to make controls and inspector flush with edges

### LINKED ISSUE #453: Dock controls to sides of window and remove headers
image
[app-chrome.html.txt](https://github.com/ProcessMaker/modeler/files/3335505/app-chrome.html.txt)

### PR DESCRIPTION
**Pull request by chipit24**
Fixes #453.

Screenshot of fix: 
Screen Shot 2019-06-27 at 3 19 08 PM

Associated PR on `processmaker`: https://github.com/ProcessMaker/processmaker/pull/2048

### CODE REVIEW

**Comment by velkymx** [comment]
Can we do this? Remove the toolbar?

image

**Comment by chipit24** [comment]
Yup! I like that.

**Comment by velkymx** [comment]
@chipit24 don't forget to reduce the fonts in the toolbars to max of 14px (14px | 0.875em | 87.5% | 11pt)

**Comment by chipit24** [comment]
@velkymx I've moved the save button up; that change was required in the `processmaker` PR though: https://github.com/ProcessMaker/processmaker/pull/2048#issuecomment-506784498.

@tuantruong625 and I split the UI work into separate issues. This one is for docking the columns and he has another for adjusting pool colour and font-sizes here: https://github.com/ProcessMaker/modeler/pull/447. I left a comment there.

**Pull request merged**
