### PR TITLE
FOUR-11840 | Add PM Blocks to the Shortcut Bar

### PR DESCRIPTION
**Pull request by mcraeteisha**
# Feature
Ticket: [FOUR-11840](https://processmaker.atlassian.net/browse/FOUR-11840)

This enhancement to the Process Modeler allows Designers to pin any PM Block to the Shortcut Bar. This feature simplifies the workflow for Designers seeking quick access to frequently used PM Blocks.

# How to Test
1. Go to branch `feature/FOUR-11840` in `modeler` and branch `feature/FOUR-11839` in `package-pm-blocks`
2. Have PM Blocks created.
3. Open a Process.
4. Navigate to the PM Blocks tab in the left rail of the Modeler.
5. Pin a PM Block.
	- The PM Block should appear pinned in the PM Blocks tab.
	- The PM Block should appear pinned in the 'Add Object' tab.
	- The PM Block should appear in the Shortcut Bar at the bottom of the Modeler.
6. Pin another object (not a PM Block).
	- The object should not appear pinned in the PM Blocks tab.

ci:package-pm-blocks:feature/FOUR-11839
ci:next
ci:deploy

# Code Review Checklist

- [ ]  I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ]  This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ]  This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ]  This solution fixes the bug reported in the original ticket.
- [ ]  This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ]  This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ]  This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ]  This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ]  This ticket conforms to the PRD associated with this part of ProcessMaker.

[FOUR-11840]: https://processmaker.atlassian.net/browse/FOUR-11840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by eiresendez — CHANGES_REQUESTED** [review]
Great job @mcraeteisha 
I've only noticed one detail: when the PM block has no icon, the PM block's name becomes its `alt` attribute. I wonder if we could do something about it? Also, could you update the branch with the latest from `next`?

Screenshot 2023-11-23 at 12-45-24 Edit Process - ProcessMaker

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-71a62f2fd8.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-71a62f2fd8.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-71a62f2fd8.eng.processmaker.net

**Comment by tokensPM** [comment]
QA server was successfully deployed https://ci-71a62f2fd8.eng.processmaker.net

**Review by eiresendez — APPROVED** [review]

**Pull request merged**
