### PR TITLE
FOUR-8582: Explorer Rail can be toggled with Add button on bottom rail

### PR DESCRIPTION
**Pull request by TinCodes**
## Solution
- The nodeStore has been used to toggle the explorer state across files like `explorer.vue` and `Controls.vue`.

## How to Test
Test the steps above

## Related Tickets & Packages
- [8582](https://processmaker.atlassian.net/browse/FOUR-8582)

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

ci:deploy

### CODE REVIEW

**Review by josechirivella — APPROVED** [review]
Approved but can you remove the unit test comments I did in the unit test file since we are not using a vdata anymore

**Review by devmiguelangel — APPROVED** [review]

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-c293b54277.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-c293b54277.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-c293b54277.eng.processmaker.net

**Comment by pmkerberos** [comment]
QA server was successfully deployed https://ci-c293b54277.eng.processmaker.net

**Pull request merged**
