### PR TITLE
FOUR-8799: Cannot read properties of undefined (reading 'get')>> Error appears in modeler with boundary event

### PR DESCRIPTION
**Pull request by rodriquelca**
## Issue & Reproduction Steps

Expected behavior: 
No error message should appear when elements are moved of pool to pool 

Actual behavior: 
Cannot read properties of undefined (reading 'get')>> appears when the selection with boundary en moved and the boundary can not be connected again. 

## Solution
- the pool references was missed for embedded elements (boundary events), so the solution is to update the new pool reference.

https://github.com/ProcessMaker/modeler/assets/1401911/efa6d9c8-23a5-4a55-ab9b-5e9ddc6953be

## How to Test
Test the steps above

1. Go to modeler 
3. Drag a pool
5. Add a lane on the pool 
7. Add task form with boundary event and event
9. Connect the boundary event to End event
11. Drag a second pool
13. Select the element of the first pool
15. Copy the selection
17. Paste the selection
19. Move the selection to second pool
21. Try to connect the Boundary event with the end event

## Related Tickets & Packages
- https://processmaker.atlassian.net/browse/FOUR-8777

## Code Review Checklist
- [ ] I have pulled this code locally and tested it on my instance, along with any associated packages.
- [ ] This code adheres to [ProcessMaker Coding Guidelines](https://github.com/ProcessMaker/processmaker/wiki/Coding-Guidelines).
- [ ] This code includes a unit test or an E2E test that tests its functionality, or is covered by an existing test.
- [ ] This solution fixes the bug reported in the original ticket.
- [ ] This solution does not alter the expected output of a component in a way that would break existing Processes.
- [ ] This solution does not implement any breaking changes that would invalidate documentation or cause existing Processes to fail.
- [ ] This solution has been tested with enterprise packages that rely on its functionality and does not introduce bugs in those packages.
- [ ] This code does not duplicate functionality that already exists in the framework or in ProcessMaker.
- [ ] This ticket conforms to the PRD associated with this part of ProcessMaker.

### CODE REVIEW

**Review by josechirivella — APPROVED** [review]

**Review by danloa — APPROVED** [review]

**Review by ana-mauricio — CHANGES_REQUESTED** [review]
The ticket: https://processmaker.atlassian.net/browse/FOUR-8799: Is passed
- https://processmaker.atlassian.net/browse/FOUR-8777, the ticket has the flowing error with the steps:Cannot read properties of undefined (reading '0')
image
https://github.com/ProcessMaker/modeler/assets/21198450/53d36dbb-f265-4e41-ba24-d69f10985a94
@rodriquelca @boliviacoca

**Comment by rodriquelca** [comment]
[bugfix/FOUR-8680](https://github.com/ProcessMaker/modeler/pull/1574/commits/448351678487d8e34c3d0f27c5701b1079620325) 
was merged in this branch to solve the latest observatio
cc. @ana-mauricio

**Comment by ana-mauricio** [comment]
I Checked esl pull request With the following scenarios, the error messages are no longer output, But the processes that follow the steps of ticket FOUR-8777 are corrupted so that a request cannot be started.
 1. https://processmaker.atlassian.net/browse/FOUR-8777: 
         Verify deleting the pool, but creating the elements before dropping a pool: Passed
	 Verify delete a pool with boundary event inside Passed
         Verify deleting a pool with a boundary event inside after moving to another pool: Passed
         Verify deleting a pool with a boundary event after changing the type of task: Passed
         Verify delete a pool with boundary event refresh the page: Passed
         Verify deleting a pool with a boundary event open the process: Passed
         Verify delete a pool with boundary in lanes: Passed
         Verify delete a pool with boundary in lanes and UNDO: Passed

      2. https://processmaker.atlassian.net/browse/FOUR-8680: The fix is correct 
         Verify delete a pool with boundary event inside Passed
         Verify deleting a pool with a boundary event inside after moving to another pool: Passed
         Verify deleting a pool with a boundary event after changing the type of task: Passed
         Verify delete a pool with boundary event refresh the page: Passed
         Verify deleting a pool with a boundary event open the process: Passed
         Verify delete a pool with boundary in lanes: Passed
         Verify delete a pool with boundary in lanes and UNDO: Passed

      3. https://processmaker.atlassian.net/browse/FOUR-8799
         Verify elements copied of lanes to another pool: Passed
         Verify elements cloned of lanes to another pool: Passed
         Verify elements copied of lanes to many pools: Passed


         Verify that it is possible to start a request after the changes: Failed 
image

@rodriquelca @boliviacoca

**Review by ana-mauricio — APPROVED** [review]
The fix is correct to :
- https://processmaker.atlassian.net/browse/FOUR-8777 
- https://processmaker.atlassian.net/browse/FOUR-8680
- https://processmaker.atlassian.net/browse/FOUR-8799
During the review, the following ticket was created, It is about deleting the pools in selection the process gets corrupt
 - https://processmaker.atlassian.net/browse/FOUR-8859
@rodriquelca @boliviacoca

**Comment by boliviacoca** [comment]
To complement: FOUR-8859 has been marked as known bug for Spring: https://processmaker.atlassian.net/browse/FOUR-8859?focusedCommentId=321803

**Comment by pmkerberos** [comment]
QA server was successfully deployed 2023-06-23T19:41:18+00:00

**Pull request merged**
